#!/usr/bin/env python3
"""minros wire-protokolü conformance vektör üreteci (bağımsız oracle).

Bu betik, beklenen wire byte'larını minros (C++) ve minrospy (Python)
implementasyonlarından BAĞIMSIZ olarak — yalnızca protokol spec'inden ve
Python standart kütüphanesinden (struct) — hesaplar. Böylece iki taraf da
aynı tarafsız "altın" vektörlere karşı sınanır; biri kayarsa testi kırılır.

Çıktılar:
    conformance/vectors.json   — Python testi (lib/minrospy/tests) okur
    conformance/vectors.hpp    — C++ testi (conformance/cpp) include eder

Kullanım:
    python3 conformance/generate.py
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ── Wire spec sabitleri ──────────────────────────────────────────────────────
HEADER = bytes((0x6D, 0x72, 0x6F, 0x73))  # 'm','r','o','s'


# ── Bağımsız CRC-8/SMBUS (poly=0x07, init=0x00, xorout=0x00) ─────────────────
def crc8(data: bytes) -> int:
    crc = 0
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = ((crc << 1) ^ 0x07) & 0xFF if (crc & 0x80) else (crc << 1) & 0xFF
    return crc


# ── struct format & C++ literal yardımcıları ─────────────────────────────────
_FMT = {
    "f": "<f", "i32": "<i", "i16": "<h", "i8": "<b",
    "u32": "<I", "u16": "<H", "u8": "<B", "bool": "<B",
}


def pack(ctype: str, value) -> bytes:
    if ctype == "bool":
        return struct.pack("<B", 1 if value else 0)
    return struct.pack(_FMT[ctype], value)


def cpp_literal(ctype: str, value) -> str:
    if ctype == "f":
        return f"{value!r}f"
    if ctype == "bool":
        return "true" if value else "false"
    if ctype == "u32":
        return f"{value}u"
    return str(value)


# ── Mesaj vektörleri ─────────────────────────────────────────────────────────
# Her alan: (attr_path, ctype, value). Sıralama serileştirme sırasıyla AYNI olmalı.
# Tüm float değerleri binary32'de TAM temsil edilebilir (çift-yuvarlama belirsizliği yok).
MESSAGES = [
    ("float32_zero",  "Float32",    [("value", "f", 0.0)]),
    ("float32_pos",   "Float32",    [("value", "f", 1.5)]),
    ("float32_neg",   "Float32",    [("value", "f", -2.25)]),
    ("int32_neg",     "Int32",      [("value", "i32", -100000)]),
    ("int16_neg",     "Int16",      [("value", "i16", -1000)]),
    ("int8_neg",      "Int8",       [("value", "i8", -5)]),
    ("uint32_max",    "UInt32",     [("value", "u32", 4294967295)]),
    ("uint16_max",    "UInt16",     [("value", "u16", 65535)]),
    ("uint8_max",     "UInt8",      [("value", "u8", 255)]),
    ("bool_true",     "Bool",       [("value", "bool", True)]),
    ("bool_false",    "Bool",       [("value", "bool", False)]),
    ("vector3",       "Vector3",    [("x", "f", 1.5), ("y", "f", -2.25), ("z", "f", 0.125)]),
    ("quaternion",    "Quaternion", [("x", "f", 0.0), ("y", "f", 0.0), ("z", "f", 0.0), ("w", "f", 1.0)]),
    ("twist",         "Twist", [
        ("linear.x", "f", 1.5), ("linear.y", "f", -2.25), ("linear.z", "f", 0.125),
        ("angular.x", "f", -0.0625), ("angular.y", "f", 256.0), ("angular.z", "f", 1024.5),
    ]),
    ("pid_gains",     "PidGains",   [("kp", "f", 0.5), ("ki", "f", 0.125), ("kd", "f", -3.25)]),
]


def message_bytes(fields) -> bytes:
    return b"".join(pack(ctype, value) for _, ctype, value in fields)


# ── CRC vektörleri ───────────────────────────────────────────────────────────
CRC8 = [
    ("empty", b""),
    ("zero", bytes([0x00])),
    ("check_123456789", b"123456789"),  # CRC-8/SMBUS standart kontrol değeri = 0xF4
    ("header", HEADER),
    ("data_field", bytes([0x05, 0x00, 0x01, 0x02, 0x03, 0x04])),
]


# ── Frame vektörleri ─────────────────────────────────────────────────────────
# (ch_id, seq, payload). DATA = [ch_id, seq] + payload. Hem C++ (Framer head yolu)
# hem Python (Framer.build(ch_id, seq, payload)) aynı wire çıktısını üretmeli.
FRAMES = [
    ("basic",   0x05, 0x00, bytes([0x01, 0x02, 0x03, 0x04])),
    ("max_ch",  0xF9, 0x11, bytes([0xAA])),
    ("seq_wrap", 0x00, 0xFF, bytes([0xDE, 0xAD, 0xBE, 0xEF])),
]


def frame_bytes(ch_id: int, seq: int, payload: bytes) -> bytes:
    data = bytes([ch_id, seq]) + payload
    return HEADER + bytes([len(data)]) + data + bytes([crc8(data)])


# ── JSON üretimi ─────────────────────────────────────────────────────────────
def build_json() -> dict:
    return {
        "_comment": "AUTO-GENERATED by conformance/generate.py — protokol spec'inden bağımsız oracle.",
        "crc8": [
            {"name": name, "data": data.hex(), "crc": crc8(data)}
            for name, data in CRC8
        ],
        "messages": [
            {
                "name": name,
                "type": mtype,
                "fields": [[path, ctype, value] for path, ctype, value in fields],
                "bytes": message_bytes(fields).hex(),
            }
            for name, mtype, fields in MESSAGES
        ],
        "frames": [
            {
                "name": name,
                "ch_id": ch_id,
                "seq": seq,
                "payload": payload.hex(),
                "frame": frame_bytes(ch_id, seq, payload).hex(),
            }
            for name, ch_id, seq, payload in FRAMES
        ],
    }


# ── C++ header üretimi ───────────────────────────────────────────────────────
def _byte_array(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02X}" for b in data) if data else "0"
    return f"static const uint8_t {name}[] = {{ {body} }};"


def build_hpp() -> str:
    L: list[str] = []
    L.append("#pragma once")
    L.append("// AUTO-GENERATED by conformance/generate.py — DO NOT EDIT.")
    L.append("// minros (C++) tarafını tarafsız conformance vektörlerine karşı sınar.")
    L.append("#include <cstdint>")
    L.append("#include <minros/interfaces/std_msgs/primitives.hpp>")
    L.append("#include <minros/interfaces/geometry_msgs/vector3.hpp>")
    L.append("#include <minros/interfaces/geometry_msgs/quaternion.hpp>")
    L.append("#include <minros/interfaces/geometry_msgs/twist.hpp>")
    L.append("#include <minros/interfaces/std_msgs/pid_gains.hpp>")
    L.append("")
    L.append("namespace conformance {")
    L.append("")

    # ── CRC8 ──
    L.append("struct Crc8Vec { const char* name; const uint8_t* data; uint32_t len; uint8_t crc; };")
    for i, (name, data) in enumerate(CRC8):
        L.append(_byte_array(f"crc8_{i}_data", data))
    L.append("static const Crc8Vec crc8_vectors[] = {")
    for i, (name, data) in enumerate(CRC8):
        L.append(f'    {{ "{name}", crc8_{i}_data, {len(data)}, 0x{crc8(data):02X} }},')
    L.append("};")
    L.append(f"static const uint32_t crc8_count = {len(CRC8)};")
    L.append("")

    # ── FRAMES ──
    L.append("struct FrameVec { const char* name; uint8_t ch_id; uint8_t seq;"
             " const uint8_t* payload; uint32_t payload_len;"
             " const uint8_t* frame; uint32_t frame_len; };")
    for i, (name, ch_id, seq, payload) in enumerate(FRAMES):
        L.append(_byte_array(f"frame_{i}_payload", payload))
        L.append(_byte_array(f"frame_{i}_frame", frame_bytes(ch_id, seq, payload)))
    L.append("static const FrameVec frame_vectors[] = {")
    for i, (name, ch_id, seq, payload) in enumerate(FRAMES):
        fr = frame_bytes(ch_id, seq, payload)
        L.append(f'    {{ "{name}", 0x{ch_id:02X}, 0x{seq:02X},'
                 f' frame_{i}_payload, {len(payload)}, frame_{i}_frame, {len(fr)} }},')
    L.append("};")
    L.append(f"static const uint32_t frame_count = {len(FRAMES)};")
    L.append("")

    # ── MESSAGES (beklenen byte'lar + üreteç tarafından yazılan kurulum kodu) ──
    for name, mtype, fields in MESSAGES:
        L.append(_byte_array(f"msg_{name}_exp", message_bytes(fields)))
    L.append("")
    L.append("// run_message_checks: her vektör için minros mesajını kurar ve")
    L.append("// `check(name, msg, expected, expected_len)` çağırır (generic lambda).")
    L.append("template<class CheckFn>")
    L.append("inline void run_message_checks(CheckFn check) {")
    L.append("    using namespace minros::interfaces::std_msgs;")
    L.append("    using namespace minros::interfaces::geometry_msgs;")
    for name, mtype, fields in MESSAGES:
        L.append("    {")
        L.append(f"        {mtype} m{{}};")
        for path, ctype, value in fields:
            L.append(f"        m.{path} = {cpp_literal(ctype, value)};")
        L.append(f'        check("{name}", m, msg_{name}_exp, sizeof(msg_{name}_exp));')
        L.append("    }")
    L.append("}")
    L.append("")
    L.append("}  // namespace conformance")
    L.append("")
    return "\n".join(L)


def main() -> None:
    (HERE / "vectors.json").write_text(
        json.dumps(build_json(), indent=2, ensure_ascii=False) + "\n"
    )
    (HERE / "vectors.hpp").write_text(build_hpp())
    print(f"wrote {HERE/'vectors.json'}")
    print(f"wrote {HERE/'vectors.hpp'}")


if __name__ == "__main__":
    main()
