#pragma once
// AUTO-GENERATED by conformance/generate.py — DO NOT EDIT.
// minros (C++) tarafını tarafsız conformance vektörlerine karşı sınar.
#include <cstdint>
#include <minros/interfaces/std_msgs/primitives.hpp>
#include <minros/interfaces/geometry_msgs/vector3.hpp>
#include <minros/interfaces/geometry_msgs/quaternion.hpp>
#include <minros/interfaces/geometry_msgs/twist.hpp>
#include <minros/interfaces/std_msgs/pid_gains.hpp>

namespace conformance {

struct Crc8Vec { const char* name; const uint8_t* data; uint32_t len; uint8_t crc; };
static const uint8_t crc8_0_data[] = { 0 };
static const uint8_t crc8_1_data[] = { 0x00 };
static const uint8_t crc8_2_data[] = { 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39 };
static const uint8_t crc8_3_data[] = { 0x6D, 0x72, 0x6F, 0x73 };
static const uint8_t crc8_4_data[] = { 0x05, 0x00, 0x01, 0x02, 0x03, 0x04 };
static const Crc8Vec crc8_vectors[] = {
    { "empty", crc8_0_data, 0, 0x00 },
    { "zero", crc8_1_data, 1, 0x00 },
    { "check_123456789", crc8_2_data, 9, 0xF4 },
    { "header", crc8_3_data, 4, 0x72 },
    { "data_field", crc8_4_data, 6, 0x6E },
};
static const uint32_t crc8_count = 5;

struct FrameVec { const char* name; uint8_t ch_id; uint8_t seq; const uint8_t* payload; uint32_t payload_len; const uint8_t* frame; uint32_t frame_len; };
static const uint8_t frame_0_payload[] = { 0x01, 0x02, 0x03, 0x04 };
static const uint8_t frame_0_frame[] = { 0x6D, 0x72, 0x6F, 0x73, 0x06, 0x05, 0x00, 0x01, 0x02, 0x03, 0x04, 0x6E };
static const uint8_t frame_1_payload[] = { 0xAA };
static const uint8_t frame_1_frame[] = { 0x6D, 0x72, 0x6F, 0x73, 0x03, 0xF9, 0x11, 0xAA, 0x4B };
static const uint8_t frame_2_payload[] = { 0xDE, 0xAD, 0xBE, 0xEF };
static const uint8_t frame_2_frame[] = { 0x6D, 0x72, 0x6F, 0x73, 0x06, 0x00, 0xFF, 0xDE, 0xAD, 0xBE, 0xEF, 0xF3 };
static const FrameVec frame_vectors[] = {
    { "basic", 0x05, 0x00, frame_0_payload, 4, frame_0_frame, 12 },
    { "max_ch", 0xF9, 0x11, frame_1_payload, 1, frame_1_frame, 9 },
    { "seq_wrap", 0x00, 0xFF, frame_2_payload, 4, frame_2_frame, 12 },
};
static const uint32_t frame_count = 3;

static const uint8_t msg_float32_zero_exp[] = { 0x00, 0x00, 0x00, 0x00 };
static const uint8_t msg_float32_pos_exp[] = { 0x00, 0x00, 0xC0, 0x3F };
static const uint8_t msg_float32_neg_exp[] = { 0x00, 0x00, 0x10, 0xC0 };
static const uint8_t msg_int32_neg_exp[] = { 0x60, 0x79, 0xFE, 0xFF };
static const uint8_t msg_int16_neg_exp[] = { 0x18, 0xFC };
static const uint8_t msg_int8_neg_exp[] = { 0xFB };
static const uint8_t msg_uint32_max_exp[] = { 0xFF, 0xFF, 0xFF, 0xFF };
static const uint8_t msg_uint16_max_exp[] = { 0xFF, 0xFF };
static const uint8_t msg_uint8_max_exp[] = { 0xFF };
static const uint8_t msg_bool_true_exp[] = { 0x01 };
static const uint8_t msg_bool_false_exp[] = { 0x00 };
static const uint8_t msg_vector3_exp[] = { 0x00, 0x00, 0xC0, 0x3F, 0x00, 0x00, 0x10, 0xC0, 0x00, 0x00, 0x00, 0x3E };
static const uint8_t msg_quaternion_exp[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F };
static const uint8_t msg_twist_exp[] = { 0x00, 0x00, 0xC0, 0x3F, 0x00, 0x00, 0x10, 0xC0, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x80, 0xBD, 0x00, 0x00, 0x80, 0x43, 0x00, 0x10, 0x80, 0x44 };
static const uint8_t msg_pid_gains_exp[] = { 0x00, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x50, 0xC0 };

// run_message_checks: her vektör için minros mesajını kurar ve
// `check(name, msg, expected, expected_len)` çağırır (generic lambda).
template<class CheckFn>
inline void run_message_checks(CheckFn check) {
    using namespace minros::interfaces::std_msgs;
    using namespace minros::interfaces::geometry_msgs;
    {
        Float32 m{};
        m.value = 0.0f;
        check("float32_zero", m, msg_float32_zero_exp, sizeof(msg_float32_zero_exp));
    }
    {
        Float32 m{};
        m.value = 1.5f;
        check("float32_pos", m, msg_float32_pos_exp, sizeof(msg_float32_pos_exp));
    }
    {
        Float32 m{};
        m.value = -2.25f;
        check("float32_neg", m, msg_float32_neg_exp, sizeof(msg_float32_neg_exp));
    }
    {
        Int32 m{};
        m.value = -100000;
        check("int32_neg", m, msg_int32_neg_exp, sizeof(msg_int32_neg_exp));
    }
    {
        Int16 m{};
        m.value = -1000;
        check("int16_neg", m, msg_int16_neg_exp, sizeof(msg_int16_neg_exp));
    }
    {
        Int8 m{};
        m.value = -5;
        check("int8_neg", m, msg_int8_neg_exp, sizeof(msg_int8_neg_exp));
    }
    {
        UInt32 m{};
        m.value = 4294967295u;
        check("uint32_max", m, msg_uint32_max_exp, sizeof(msg_uint32_max_exp));
    }
    {
        UInt16 m{};
        m.value = 65535;
        check("uint16_max", m, msg_uint16_max_exp, sizeof(msg_uint16_max_exp));
    }
    {
        UInt8 m{};
        m.value = 255;
        check("uint8_max", m, msg_uint8_max_exp, sizeof(msg_uint8_max_exp));
    }
    {
        Bool m{};
        m.value = true;
        check("bool_true", m, msg_bool_true_exp, sizeof(msg_bool_true_exp));
    }
    {
        Bool m{};
        m.value = false;
        check("bool_false", m, msg_bool_false_exp, sizeof(msg_bool_false_exp));
    }
    {
        Vector3 m{};
        m.x = 1.5f;
        m.y = -2.25f;
        m.z = 0.125f;
        check("vector3", m, msg_vector3_exp, sizeof(msg_vector3_exp));
    }
    {
        Quaternion m{};
        m.x = 0.0f;
        m.y = 0.0f;
        m.z = 0.0f;
        m.w = 1.0f;
        check("quaternion", m, msg_quaternion_exp, sizeof(msg_quaternion_exp));
    }
    {
        Twist m{};
        m.linear.x = 1.5f;
        m.linear.y = -2.25f;
        m.linear.z = 0.125f;
        m.angular.x = -0.0625f;
        m.angular.y = 256.0f;
        m.angular.z = 1024.5f;
        check("twist", m, msg_twist_exp, sizeof(msg_twist_exp));
    }
    {
        PidGains m{};
        m.kp = 0.5f;
        m.ki = 0.125f;
        m.kd = -3.25f;
        check("pid_gains", m, msg_pid_gains_exp, sizeof(msg_pid_gains_exp));
    }
}

}  // namespace conformance
